# -*- coding: utf-8 -*-
"""untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/helena07nv-web/1917cf65b36de4a4ee4b49e94a5d184f/untitled4.ipynb
"""

import pandas as pd

dados = {
    'Nome': ['João', 'Maria', 'Pedro', 'Ana'],
    'Idade': [25, 30, 35, 47],
    'Salarios': [5000, 2000, 1300, 800],
}

df = pd.DataFrame(dados)

df.describe()

df.shape[1]

